### ISSUE TITLE
第一步已经更新，第二步更新，SQL报错了

### ISSUE THREAD

**Issue by hellozhang** [yeyedas/datadown-tiantianfund#1]
File "D:\PYJect\venv\lib\site-packages\pandas\io\sql.py", line 2054, in execute
    cur = self.con.cursor()
AttributeError: 'int' object has no attribute 'cursor'

panda 用哪个版本

**Comment by hellozhang** [comment]
python 是哪个版本

**Comment by hellozhang** [comment]
PS D:\NET\datadown-tiantianfund> python fund_list_down.py --account root --password 123456 --host localhost --post 3306 --database fund
fund_list更新完成
PS D:\NET\datadown-tiantianfund> python fund_data_down.py --account root --password 123456 --host localhost --post 3306 --database fund --update False
  0%|                                                                                                                                       | 0/6788 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\NET\datadown-tiantianfund\fund_data_down.py", line 160, in <module>
    main_command()
  File "D:\NET\datadown-tiantianfund\venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\NET\datadown-tiantianfund\venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\NET\datadown-tiantianfund\venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\NET\datadown-tiantianfund\venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\NET\datadown-tiantianfund\fund_data_down.py", line 142, in main_command
    list_error = get_fund_data(fund_list, date_last, engine, name)
  File "D:\NET\datadown-tiantianfund\fund_data_down.py", line 80, in get_fund_data
    date_last = pd.read_sql('SELECT MAX(date) FROM %s_fund_data WHERE fund=\'%s\''%(name,fund), engine).iloc[-1, 0]
  File "D:\NET\datadown-tiantianfund\venv\lib\site-packages\pandas\io\sql.py", line 602, in read_sql
    return pandas_sql.read_query(
  File "D:\NET\datadown-tiantianfund\venv\lib\site-packages\pandas\io\sql.py", line 2116, in read_query
    cursor = self.execute(*args)
  File "D:\NET\datadown-tiantianfund\venv\lib\site-packages\pandas\io\sql.py", line 2054, in execute
    cur = self.con.cursor()
**### AttributeError: 'int' object has no attribute 'cursor'**
PS D:\NET\datadown-tiantianfund>

**Comment by yeyedas** [comment]
抱歉，这是我写的代码问题
问题已经修正，请重新Clone。

**Comment by hellozhang** [comment]
多谢回复，方便加v吗，hizhangxf

**Comment by yeyedas** [comment]
OK
